tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/php"
tap "homebrew/services"
brew "readline"
brew "bash"
brew "bash-completion"
brew "brotli"
brew "carthage"
brew "git"
brew "imagemagick"
brew "memcached", restart_service: true
brew "libyaml"
brew "mysql", restart_service: true
brew "nginx", restart_service: true
brew "node"
brew "php@7.0"
brew "phplint"
brew "ruby"
brew "telnet"
brew "thefuck"
brew "wget"
