tap "homebrew/bundle"
tap "homebrew/services"
brew "atuin"
brew "bash"
brew "bash-completion@2"
brew "readline"
brew "brotli"
brew "carthage"
brew "chezmoi"
brew "fzf"
brew "git"
brew "gh"
brew "imagemagick"
brew "just"
brew "libyaml"
brew "memcached", restart_service: true
brew "mise"
brew "nginx", restart_service: true
brew "node"
brew "php"
brew "pixlet"
brew "ripgrep"
brew "ruby"
brew "starship"
brew "telnet"
brew "thefuck"
brew "wget"
brew "zoxide"
