source ~/etc/bash/paths.bash
source ~/etc/bash/applications.bash
source ~/etc/bash/fuck.bash
source ~/etc/bash/machine.bash
source ~/etc/bash/profile.bash
source ~/etc/bash/functions.bash
source ~/etc/bash/git.bash
source ~/etc/bash/node.bash
source ~/etc/bash/pants.bash
source ~/etc/bash/ruby.bash
source ~/etc/bash/sourcecontrol.bash
source ~/etc/bash/macosx.bash
source ~/etc/bash/scala.bash
source ~/.extras.bash